services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    networks:
      - app-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8000:8000"
    networks:
      - app-network

  db:
    image: mysql:8.0
    container_name: mysql-db
    restart: always
    ports:
      - "4407:3306"
    environment:
      MYSQL_ROOT_PASSWORD: Theo68150
      MYSQL_DATABASE: etodo
      MYSQL_USER: theo
      MYSQL_PASSWORD: Theo68150
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-pTheo68150"]
      timeout: 5s
      retries: 10
      interval: 3s

    volumes:
      - ./backend/etodo.sql:/docker-entrypoint-initdb.d/init.sql
      - db_data:/var/lib/mysql
    networks:
      - app-network

volumes:
  db_data:

networks:
  app-network:
    driver: bridge